var targetHostName = args[0];
var moneyThresh = getServerMaxMoney(targetHostName) * 0.75;
var securityThresh = getServerMinSecurityLevel(targetHostName) + 5;

hackTargetHost(targetHostName)

function hackTargetHost(target) {
    while (true) {
        if (getServerSecurityLevel(target) > securityThresh) {
            weaken(target);
        } else if (getServerMoneyAvailable(target) < moneyThresh) {
            grow(target);
        } else {
            hack(target);
        }
    }
}
